# Этап 1: сборка зависимостей
FROM python:3.12-slim as builder
WORKDIR /app

#Установка компилятора gcc
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

# Создание виртуального окружения
RUN python -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

# Копирование зависимостей
COPY requirements.txt ./

# Установка зависимостей с использованием кеша pip
RUN --mount=type=cache,target=~/.cache/pip pip install -r requirements.txt


# Этап 2: финальный образ
FROM python:3.12-slim as worker
WORKDIR /app

# Создание непривилегированного пользователя
RUN addgroup --system python && \
    adduser --system --disabled-password --ingroup python python && \
    chown python:python /app
USER python

# Копируем виртуальное окружение из builder
COPY --chown=python:python --from=builder /app/venv ./venv
COPY --chown=python:python . .

# Используем зависимости из виртуального окружения
ENV PATH="/app/venv/bin:$PATH"

# Запуск приложения через uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
